ARG BASE_IMAGE
ARG ROS_DISTRO

FROM ${BASE_IMAGE}

#For ROS
ENV ROS_DISTRO=${ROS_DISTRO}

# 
# setup entrypoint
#
# COPY scripts/ros_entrypoint.sh /ros_entrypoint.sh
# RUN echo 'source /ros_entrypoint_slave.sh' >> /root/.bashrc
# RUN chmod 755 /ros_entrypoint.sh
# ENTRYPOINT ["/ros_entrypoint_slave.sh"]
# CMD ["bash"]

WORKDIR /root